build:
  image: golang
  commands:
    - go get
    - go build
    - go test

publish:
  docker: 
    username: linuskendall
    password: $$DOCKER_PASSWORD
    email: git@linuskendall.com
    repo: linuskendall/deploy-test
    file: Dockerfile
    insecure: false
    tag:
        - latest
        - $$COMMIT
